version: '3.8'

services:
  ai-chatbot:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (uncomment for development)
  # ai-chatbot-dev:
  #   build:
  #     context: .
  #     target: build
  #   ports:
  #     - "3000:3000"  # React dev server
  #     - "3001:3001"  # Node.js server
  #   environment:
  #     - NODE_ENV=development
  #     - JWT_SECRET=dev-secret-key
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/client/node_modules
  #     - /app/server/node_modules
  #   command: npm run dev 